from django.urls import path
from . import views

urlpatterns=[
    path('', views.redirect, name='redirect'),
    path('index_student', views.index_student, name='index_student'),
    path('index_manager', views.index_manager, name='index_manager'),
    path('index_instructor', views.index_instructor, name='index_instructor'),
    path('manager_login', views.manager_login, name='manager_login'),
    path('student_login', views.student_login, name='student_login'),
    path('instructor_login', views.instructor_login, name='instructor_login'),
    path('manager', views.db_manager_homepage, name='db_manager_homepage'),
    path('instructor', views.instructor_homepage, name='instructor_homepage'),
    path('student', views.student_homepage, name='student_homepage'),
    path('add_student', views.add_student, name='add_student'),
    path('add_instructor', views.add_instructor, name='add_instructor'),
    path('delete_student', views.delete_student, name='delete_student'),
    path('update_title', views.update_title, name='update_title'),
    path('studentlist', views.view_students, name='view_students'),
    path('instructorlist', views.view_instructors, name='view_instructors'),
    path('gradelist', views.view_grades, name='view_grades'),
    path('courses', views.view_courses, name='view_courses'),
    path('averageGrade', views.view_avg_grade, name='view_avg_grade'),
    path('availableClassrooms', views.view_available_classrooms, name='view_available_classrooms'),
    path('add_course', views.add_course, name='add_course'),
    path('add_prerequisite', views.add_prerequisite, name='add_prerequisite'),
    path('selfCourses', views.view_self_courses, name='view_self_courses'),
    path('studentsInTheCourse', views.view_students_byCourseId, name='view_students_byCourseId'),
    path('update_course', views.update_course, name='update_course'),
    path('give_grade', views.give_grade, name='give_grade'),
    path('allCourses', views.view_all_courses, name='view_all_courses'),
    path('take_course', views.take_course, name='take_course'),
    path('takenCourses', views.view_taken_courses, name='view_taken_courses'),
    path('search', views.search, name='search'),
    path('filter', views.filter_courses, name='filter_courses'),
]